Update links in README
RsaCtfTool/RsaCtfTool pull request #468
Opened 2024-02-08 17:26 UTC by upiter

- More recent repo with current **msieve** version (1.54 from 2022) with updated docs in markdown. Existing link leads to 14 year old repo with outdated version.

- Removed `.git` from **yafu** link.

2024-02-09 17:24 UTC, daedalus requested changes
Please do not point url dependencies to your own forks.
If you want to contribute, send a PR with your contributions to the original repos.
I'm only accepting the change in the yafu url for now.
Please revert back the change from upiter to radii, and I'll happy to accept the PR.
Thanks

2024-02-14 03:06 UTC, daedalus commented
I'm closing this since no further commits were added.

2024-02-14 03:06 UTC, closed without merging

2024-02-14 15:02 UTC, upiter commented
Dear Darío, my intention was to provide a link to the **updated** msieve repo on GitHub, which is a clone (or mirror) of the official repo on SourceForge.


## Links

- [msieve.sourceforge.net](https://sourceforge.net/p/msieve/code/HEAD/tree/trunk/) — official msieve repo on SourceForge maintained by Jason Papadopoulos himself ([jasonp_sf](https://sourceforge.net/u/jasonp_sf/profile))

- [github.com/upiter/msieve](https://github.com/upiter/msieve) — unofficial msieve repo clone with nice updated docs in markdown. This repo contains all [commits](https://github.com/upiter/msieve/commits/master/) from the official msieve SVN on SourceForge. README file has links to official repo ([one](https://github.com/upiter/msieve/blob/master/README.md?plain=1#L53), [two](https://github.com/upiter/msieve/blob/master/README.md?plain=1#L481), [three](https://github.com/upiter/msieve/blob/master/README.md?plain=1#L483)).

I really don't understand why keeping an unofficial, unmaintained and abandoned repo (latest [commit](https://github.com/radii/msieve/commits/master/) was made on 21 February 2011) is better than having a link to an updated, unofficial, maintained GiHub repo.

I'm not comfortable navigating SourceForge repos, as their design lacks some usability. So I suppose it's much more comfortable for GitHub users to read information the modern way.


## Request for changes

> If you want to contribute, send a PR with your contributions to the original repos.

Please explain what you mean by this request. The official repo is on SourceForge, it's the original.
If by "original repos" you mean the abandoned one, then I don't see any easy technical way to update that repo through PR, it's much easier to do it by the repo owner himself, but he's been abandoning his repo for 13 years. There have been hundreds (400+) of commits since then.


> I'm only accepting the change in the yafu url for now.

The `.git` suffix was fixed with the main msieve repo link update, so I don't think it's really important to fix it, as GitHub redirects the link correctly.


## Security issues

If you care about security and the integrity of the original commits, you could compare different repos and see that only markdown files are changed. If you need detailed instructions on how to compare `git` (GitHub) and `svn` (SourceForge) repos, I could create such a document.


## Solution

May be it's better to provide a link to official msieve repo on SourceForge instead of GitHub mirror?


Best wishes, J.

2024-02-14 17:07 UTC, daedalus commented
The reason that I'm not accepting your link update is beacuse i'ts pointing to your own fork (think of supply chain attack).

If you still want to contribute you can send a PR with your contributions to https://github.com/RsaCtfTool/msieve I'll happy to merge.

2024-02-14 17:20 UTC, upiter commented
Dear Darío, I suggested using a link to the official repo on SourceForge as a solution. Feel free to ignore my repo if you think it's risky. 

> If you still want to contribute you can send a PR with your contributions to [RsaCtfTool/msieve](https://github.com/RsaCtfTool/msieve) I'll be happy to merge.

I already explained in my [previous comment](https://github.com/RsaCtfTool/RsaCtfTool/pull/468#issuecomment-1944014293) about repo you forked:

------ >8 ------

I don't see any easy technical way to update that repo through PR, it's much easier to do it by the repo owner himself, but he's been **abandoning his repo for 13 years**. There have been **hundreds** (400+) of commits since then.

------ 8< ------

It's not worth spending time updating this outdated repo, imho.